<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CreateAccount</name>
   <tag></tag>
   <elementGuidId>4cb81945-4d7f-481d-92ef-d9a0e04f0cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[data-qa=create-account]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
