<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_MobileNumber</name>
   <tag></tag>
   <elementGuidId>791231d2-a3f7-488d-8b67-74acc901ba8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile_number</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
