<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_State</name>
   <tag></tag>
   <elementGuidId>e3a7587b-52c3-4e8f-a06e-583bf5a030cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#state</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
