<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_FirstName</name>
   <tag></tag>
   <elementGuidId>cabdec16-9545-4184-b788-5e848e4aa9f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#first_name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
